# Site settings
title: Yasin Güzeldal
email: yasin@guezeldal.com
description: Yasin Güzeldals design blog
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yasin.guezeldal.com" # the base hostname & protocol for your site
twitter_username: yasinguezeldal
github_username:  yguezeldal

# Build settings
markdown: kramdown
permalink: /:categories/:title

sass:
  sass_dir: assets/sass
