# Site settings
title: Yasin Güzeldal
email: yasin@guezeldal.com
name: Yasin Güzeldal blog
description: Blog about design, code and everything about the web.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://yasin.guzeldal.com" # the base hostname & protocol for your site
locale: "en_US"
icon: "/assets/img/yasinguzeldalcom.jpg"
author:
  github:       yguezeldal
  twitter:      yasinguezeldal
  facebook:     yasin.guezel
  google_plus:  103043894926255935170

fb_admins:      1188474267
fb_appid:       1227999463883919

collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
    defaults:
      - scope:
          path: ""
          type: portfolio

# Build settings
markdown: kramdown
permalink: /:categories/:title
exclude: [Gemfile, Gemfile.lock, node_modules, Gruntfile.coffee, package.json, README.md]

sass:
  sass_dir: assets/css
