# Site settings
title: Yasin Güzeldals Blog
email: yasin@guezeldal.com
description: > Yasin Güzeldals design blog
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yguezeldal.github.io" # the base hostname & protocol for your site
twitter_username: yasinguezeldal
github_username:  yguezeldal

# Build settings
markdown: kramdown
